package com.signbridge.app.translation

import android.content.Context
import android.util.Log
import com.signbridge.app.model.AslTranslation
import com.signbridge.app.model.TranslationMethod
import org.json.JSONArray
import java.io.InputStream

/**
 * 3-tier ASL translation engine.
 *
 * Tier 1: Pattern hash table with template slots (instant, ~40 patterns hardcoded
 *         + full set from assets/translation/patterns.json when available)
 * Tier 2: Vector similarity via MiniLM embeddings + FAISS (fast, ~100ms)
 * Tier 3: Small fine-tuned model (T5-small ONNX) (slower, experimental)
 *
 * Falls through tiers until a confident result is found.
 * Never fails: worst case returns fingerspell-only fallback.
 *
 * Artifacts (from Python build: python -m translation.export):
 *   assets/translation/patterns.json
 *   assets/translation/faiss.index
 *   assets/translation/index_map.json
 *   assets/translation/minilm.onnx
 *   assets/translation/t5_encoder_int8.onnx (Tier 3, experimental)
 *   assets/translation/t5_decoder_int8.onnx (Tier 3, experimental)
 */
class AslTranslationEngine(private val context: Context) {

    companion object {
        private const val TAG = "AslTranslation"
        const val VECTOR_CONFIDENCE_THRESHOLD = 0.75f
        private const val PATTERNS_ASSET = "translation/patterns.json"
    }

    private val patternHash = PatternHashTable()
    private var vectorIndex: VectorSimilarityIndex? = null

    // Tier 3 — initialized when T5 ONNX checkpoint is present
    // private var t5Model: T5GlossModel? = null

    fun initialize() {
        // Tier 1: Load pattern hash table
        val loaded = patternHash.loadFromAssets(context, PATTERNS_ASSET)
        if (!loaded) {
            Log.w(TAG, "patterns.json not found in assets — using hardcoded defaults")
            patternHash.loadDefaults()
        }
        Log.i(TAG, "Tier 1: ${patternHash.patternCount} patterns")

        // Tier 2: Load pre-computed vector index
        vectorIndex = VectorSimilarityIndex(context)
        if (vectorIndex!!.load()) {
            Log.i(TAG, "Tier 2: ${vectorIndex!!.vectorCount} vectors loaded")
        } else {
            Log.w(TAG, "Tier 2: vector index not available — will skip to grammar rules")
            vectorIndex = null
        }

        // Tier 3: T5-small ONNX (not yet available)
        // t5Model = T5GlossModel(context).apply { load() }
    }

    /**
     * Translate an English sentence to ASL gloss tokens.
     * Falls through 3 tiers in order; always returns a result.
     */
    fun translate(englishSentence: String): AslTranslation? {
        val normalized = normalize(englishSentence)

        // Tier 1: Pattern hash (instant)
        val t1 = patternHash.match(normalized)
        if (t1 != null) {
            Log.d(TAG, "T1 hit: \"$normalized\" → ${t1.glossTokens}")
            return t1
        }

        // Tier 2: Vector similarity (cosine over pre-embedded patterns)
        vectorIndex?.let { idx ->
            val t2 = idx.findSimilar(normalized, VECTOR_CONFIDENCE_THRESHOLD)
            if (t2 != null) {
                Log.d(TAG, "T2 hit: \"$normalized\" → ${t2.glossTokens} (conf=${t2.confidence})")
                return t2
            }
        }

        // Tier 3: Small model (TODO: wire T5GlossModel)
        // t5Model?.let { model ->
        //     val t3 = model.generateGloss(normalized)
        //     if (t3 != null) {
        //         Log.d(TAG, "T3 hit: \"$normalized\" → ${t3.glossTokens}")
        //         return t3
        //     }
        // }

        // Fallback: rule-based ASL grammar transformation.
        // Better than word-by-word SEE: applies ASL grammar rules
        // (topic-comment, WH-questions at end, negation after verb, drop articles/copulas).
        Log.d(TAG, "Fallback (grammar rules): \"$normalized\"")
        val glossTokens = AslGrammarRules.apply(normalized)
        return AslTranslation(
            glossTokens = glossTokens,
            method = TranslationMethod.FINGERSPELL_ONLY,
            confidence = 0.4f
        )
    }

    private fun normalize(sentence: String): String {
        return sentence
            .lowercase()
            .replace(Regex("[^a-z0-9\\s']"), "")
            .replace(Regex("\\s+"), " ")
            .trim()
    }
}

/**
 * Tier 1: Pattern hash table with template slots.
 *
 * Patterns use {SLOT} notation where the slot name is a valid regex group name:
 *   "i gave {PERSON} the {OBJECT}" → "{OBJECT} I GIVE-{PERSON}"
 *
 * Runtime matching: normalize input → try each pattern regex → extract slot
 * values via named capture groups → fill ASL template.
 *
 * Primary source: assets/translation/patterns.json (generated by Agent 5 Python
 * pipeline, `python -m translation.export`).
 * Fallback: loadDefaults() minimal hardcoded set for offline / first-run.
 */
class PatternHashTable {

    data class PatternEntry(
        val pattern: Regex,
        val slotNames: List<String>,
        val aslTemplate: String,
        val sourceEnglish: String
    )

    private val patterns = mutableListOf<PatternEntry>()
    val patternCount: Int get() = patterns.size

    /**
     * Load patterns from assets/translation/patterns.json.
     * Returns true if loaded successfully, false if the asset was not found.
     *
     * JSON format (array of objects):
     *   [{"english": "i want {THING}", "asl": "{THING} I WANT", "category": "request"}, ...]
     */
    fun loadFromAssets(context: Context, assetPath: String): Boolean {
        return try {
            val stream: InputStream = context.assets.open(assetPath)
            val jsonText = stream.bufferedReader().readText()
            stream.close()

            val array = JSONArray(jsonText)
            var loaded = 0
            for (i in 0 until array.length()) {
                val obj = array.getJSONObject(i)
                val english = obj.getString("english")
                val asl = obj.getString("asl")
                addPattern(english, asl)
                loaded++
            }
            Log.i("PatternHashTable", "Loaded $loaded patterns from $assetPath")
            loaded > 0
        } catch (e: Exception) {
            Log.d("PatternHashTable", "Could not load $assetPath: ${e.message}")
            false
        }
    }

    /**
     * Minimal hardcoded pattern set — used as fallback when patterns.json is absent.
     * Keep in sync with the most common patterns from translation/tier1/patterns.py.
     */
    fun loadDefaults() {
        addPattern("i gave {PERSON} the {OBJECT}", "{OBJECT} I GIVE-{PERSON}")
        addPattern("i gave you the {OBJECT}", "{OBJECT} I GIVE-YOU")
        addPattern("what is your {NOUN}", "YOUR {NOUN} WHAT")
        addPattern("what is your name", "YOUR NAME WHAT")
        addPattern("i don't understand", "UNDERSTAND I NOT")
        addPattern("i don't {VERB}", "{VERB} I NOT")
        addPattern("do you want {THING}", "{THING} YOU WANT")
        addPattern("can you help me", "YOU HELP ME CAN")
        addPattern("can you {VERB}", "YOU {VERB} CAN")
        addPattern("how are you", "YOU HOW YOU")
        addPattern("my name is {NAME}", "MY NAME {NAME}")
        addPattern("i want {THING}", "{THING} I WANT")
        addPattern("i need {THING}", "{THING} I NEED")
        addPattern("i need help", "HELP I NEED")
        addPattern("i am {ADJECTIVE}", "{ADJECTIVE} I")
        addPattern("i am happy", "HAPPY I")
        addPattern("i am tired", "TIRED I")
        addPattern("i am sick", "SICK I")
        addPattern("i am deaf", "DEAF I")
        addPattern("i am going to {PLACE}", "{PLACE} GO I")
        addPattern("i am at {PLACE}", "AT {PLACE} I")
        addPattern("where is the {PLACE}", "{PLACE} WHERE")
        addPattern("where is {THING}", "{THING} WHERE")
        addPattern("where is the bathroom", "BATHROOM WHERE")
        addPattern("where is the hospital", "HOSPITAL WHERE")
        addPattern("where are you from", "YOU FROM WHERE")
        addPattern("when is {EVENT}", "{EVENT} WHEN")
        addPattern("how much does {THING} cost", "{THING} COST HOW-MUCH")
        addPattern("how much is this", "THIS COST HOW-MUCH")
        addPattern("i need a doctor", "DOCTOR I NEED")
        addPattern("call an ambulance", "AMBULANCE CALL")
        addPattern("i am in pain", "PAIN I")
        addPattern("i am allergic to {THING}", "{THING} ALLERGIC I")
        addPattern("please {VERB}", "PLEASE {VERB}")
        addPattern("can i have {THING}", "{THING} I CAN HAVE")
        addPattern("nice to meet you", "MEET YOU NICE")
        addPattern("thank you", "THANK-YOU")
        addPattern("you're welcome", "WELCOME")
        addPattern("i'm sorry", "SORRY I")
        addPattern("excuse me", "EXCUSE-ME")
        addPattern("i think {CLAUSE}", "{CLAUSE} I THINK")
        addPattern("i know {CLAUSE}", "{CLAUSE} I KNOW")
        addPattern("i don't know", "KNOW I NOT")
        addPattern("what happened", "HAPPEN WHAT")
        addPattern("what time is it", "TIME WHAT")
        addPattern("what are you doing", "YOU DO WHAT")
        addPattern("how old are you", "YOUR AGE WHAT")
        addPattern("do you understand", "YOU UNDERSTAND")
        addPattern("let's go to {PLACE}", "{PLACE} GO WE")
        addPattern("i can't {VERB}", "{VERB} I CAN'T")
        addPattern("i will {VERB}", "WILL I {VERB}")
        addPattern("see you later", "LATER SEE-YOU")
        addPattern("see you tomorrow", "TOMORROW SEE-YOU")
        addPattern("take care", "TAKE-CARE")
        addPattern("hello", "HELLO")
        addPattern("hi", "HELLO")
        addPattern("goodbye", "GOODBYE")
        addPattern("bye", "GOODBYE")
        addPattern("yes", "YES")
        addPattern("no", "NO")
        addPattern("maybe", "MAYBE")
        addPattern("okay", "OKAY")
        addPattern("i am lost", "LOST I")
        addPattern("emergency", "EMERGENCY")
        addPattern("it is raining", "RAIN")
        addPattern("it is cold", "COLD")
        addPattern("it is hot", "HOT")
        addPattern("the weather is nice", "WEATHER NICE")
        addPattern("i agree", "AGREE I")
        addPattern("i disagree", "DISAGREE I")
        addPattern("i don't feel well", "FEEL-WELL I NOT")
    }

    private fun addPattern(englishPattern: String, aslTemplate: String) {
        val slotRegex = Regex("\\{(\\w+)\\}")
        val slotNames = slotRegex.findAll(englishPattern)
            .map { it.groupValues[1] }
            .toList()

        // Split on slots, escape fixed parts, rejoin with capture groups
        val parts = slotRegex.split(englishPattern)
        val slotMatches = slotRegex.findAll(englishPattern).toList()

        val regexBuilder = StringBuilder("^")
        for (i in parts.indices) {
            regexBuilder.append(Regex.escape(parts[i]))
            if (i < slotMatches.size) {
                val slotName = slotMatches[i].groupValues[1]
                regexBuilder.append("(?<$slotName>.+?)")
            }
        }
        regexBuilder.append("[.?!]?$")
        val regexStr = regexBuilder.toString()

        patterns.add(
            PatternEntry(
                pattern = Regex(regexStr, RegexOption.IGNORE_CASE),
                slotNames = slotNames,
                aslTemplate = aslTemplate,
                sourceEnglish = englishPattern
            )
        )
    }

    fun match(normalizedSentence: String): AslTranslation? {
        for (entry in patterns) {
            val matchResult = entry.pattern.find(normalizedSentence) ?: continue

            val slotValues = mutableMapOf<String, String>()
            for (slot in entry.slotNames) {
                val value = try {
                    matchResult.groups[slot]?.value ?: continue
                } catch (e: Exception) {
                    continue
                }
                slotValues[slot] = value.uppercase()
            }

            var aslGloss = entry.aslTemplate
            for ((slot, value) in slotValues) {
                aslGloss = aslGloss.replace("{$slot}", value)
            }

            val glossTokens = aslGloss.split(" ").filter { it.isNotBlank() }

            return AslTranslation(
                glossTokens = glossTokens,
                method = TranslationMethod.PATTERN_HASH,
                confidence = 1.0f,
                pattern = entry.sourceEnglish
            )
        }
        return null
    }
}
