"""Tier 1: Hash table — exact sentence/phrase match + pattern templates.

Instant lookup. Returns ASL gloss if the input exactly matches a known
sentence or fits a known pattern template.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from translation.config import PATTERNS_JSON
from translation.types import TranslationMethod, TranslationResult


class HashTable:
    """Tier 1 translation: exact match and pattern templates."""

    def __init__(self, data_path: Path | None = None):
        self.exact: dict[str, list[str]] = {}
        self.patterns: list[dict] = []
        self._loaded = False
        self._data_path = data_path

    def load(self, data_path: Path | None = None) -> None:
        """Load the phrase table from JSON.

        Accepts two formats:

        Format A — generated by `python -m translation.export` (primary):
            Array of {english, asl, category} objects.
            Loaded from PATTERNS_JSON (assets/translation/patterns.json).
            224+ patterns, sorted by specificity, with {SLOT} templates.

        Format B — legacy common_phrases.json:
            Object with "exact" dict and "patterns" list.
            Kept for backwards compatibility.
        """
        path = data_path or self._data_path
        if path is None:
            # Prefer generated patterns.json; fall back to legacy file
            path = PATTERNS_JSON
            if not path.exists():
                path = Path(__file__).parent.parent / "data" / "common_phrases.json"
        if not path.exists():
            raise FileNotFoundError(
                f"No phrase table found. Run: python -m translation.export"
            )

        with open(path) as f:
            data = json.load(f)

        if isinstance(data, list):
            # Format A: [{english, asl, category}, ...]
            # Convert to internal representation:
            #   exact  = no-slot patterns (confidence 1.0)
            #   patterns = slotted patterns (confidence 0.95)
            exact: dict[str, list[str]] = {}
            patterns: list[dict] = []
            for record in data:
                # Lowercase the literal parts but preserve slot name case
                # e.g. "I gave {PERSON} the {OBJECT}" → "i gave {PERSON} the {OBJECT}"
                raw_english = record["english"].strip()
                # Slots in patterns.py are already uppercase (e.g. {OBJECT}); keep them
                english = re.sub(
                    r"(\{[^}]+\})|([^{]+)",
                    lambda m: m.group(1) if m.group(1) else m.group(2).lower(),
                    raw_english,
                ).strip()
                asl_str = record["asl"]
                asl_tokens = asl_str.split()
                if "{" not in english:
                    # Exact match entry
                    exact[english] = asl_tokens
                else:
                    # Pattern entry — convert "ASL TEMPLATE" string to token list
                    patterns.append({
                        "pattern": english,
                        "gloss": asl_tokens,
                    })
            self.exact = exact
            self.patterns = patterns
        else:
            # Format B: {exact: {}, patterns: [...]}
            self.exact = {k.lower().strip(): v for k, v in data.get("exact", {}).items()}
            self.patterns = data.get("patterns", [])

        self._loaded = True

    def _ensure_loaded(self) -> None:
        if not self._loaded:
            self.load()

    def lookup_exact(self, sentence: str) -> TranslationResult | None:
        """Try exact match against known sentences."""
        self._ensure_loaded()
        normalized = sentence.lower().strip()
        # Remove trailing punctuation
        normalized = re.sub(r"[.!?;:]+$", "", normalized).strip()

        if normalized in self.exact:
            return TranslationResult(
                asl_gloss=list(self.exact[normalized]),
                method=TranslationMethod.HASH,
                confidence=1.0,
                english=sentence,
            )
        return None

    def lookup_pattern(self, sentence: str) -> TranslationResult | None:
        """Try pattern template matching.

        Patterns use {SLOT} placeholders. Example:
          pattern: "i gave {PERSON} the {OBJECT}"
          input:   "i gave you the book"
          gloss:   ["{OBJECT}", "I", "GIVE-{PERSON}"] → ["BOOK", "I", "GIVE-YOU"]
        """
        self._ensure_loaded()
        normalized = sentence.lower().strip()
        normalized = re.sub(r"[.!?;:]+$", "", normalized).strip()

        for pattern_entry in self.patterns:
            template = pattern_entry["pattern"]
            gloss_template = pattern_entry["gloss"]

            match = self._match_pattern(template, normalized)
            if match is not None:
                # Substitute slot values into gloss
                gloss = self._substitute_gloss(gloss_template, match)
                return TranslationResult(
                    asl_gloss=gloss,
                    method=TranslationMethod.HASH,
                    confidence=0.95,  # slightly less than exact
                    english=sentence,
                    debug={"pattern": template, "slots": match},
                )
        return None

    def translate(self, sentence: str) -> TranslationResult | None:
        """Try tier 1: exact match first, then patterns."""
        result = self.lookup_exact(sentence)
        if result:
            return result
        return self.lookup_pattern(sentence)

    @staticmethod
    def _match_pattern(template: str, text: str) -> dict[str, str] | None:
        """Match text against a pattern template, returning slot values.

        Converts "{PERSON}" to a named regex group, then tries to match.
        """
        # Escape regex chars in the literal parts
        parts = re.split(r"(\{[A-Z_]+\})", template)
        regex_parts = []
        slot_names = []
        for part in parts:
            m = re.match(r"\{([A-Z_]+)\}", part)
            if m:
                name = m.group(1)
                slot_names.append(name)
                regex_parts.append(f"(?P<{name}>.+?)")
            else:
                regex_parts.append(re.escape(part))

        regex = "^" + "".join(regex_parts) + "$"
        match = re.match(regex, text)
        if match:
            return {name: match.group(name) for name in slot_names}
        return None

    @staticmethod
    def _substitute_gloss(gloss_template: list[str], slots: dict[str, str]) -> list[str]:
        """Substitute slot values into a gloss template."""
        result = []
        for token in gloss_template:
            substituted = token
            for slot_name, slot_value in slots.items():
                placeholder = "{" + slot_name + "}"
                if placeholder in substituted:
                    substituted = substituted.replace(placeholder, slot_value.upper())
            result.append(substituted)
        return result

    @property
    def stats(self) -> dict:
        self._ensure_loaded()
        return {
            "exact_entries": len(self.exact),
            "pattern_entries": len(self.patterns),
        }
